#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_log = 2,
  anon_sym_COMMA = 3,
  anon_sym_if = 4,
  anon_sym_elif = 5,
  anon_sym_else = 6,
  anon_sym_class = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_return = 10,
  anon_sym_const = 11,
  anon_sym_EQ = 12,
  anon_sym_DOT = 13,
  sym_literal = 14,
  sym_number = 15,
  sym_indent = 16,
  sym_dedent = 17,
  sym__newline = 18,
  sym_source_file = 19,
  sym__definition = 20,
  sym_log_statement = 21,
  sym_if_statement = 22,
  sym_elif_statement = 23,
  sym_else_statement = 24,
  sym_class_declaration = 25,
  sym__suite = 26,
  sym_class_body = 27,
  sym_method_definition = 28,
  sym_param_list = 29,
  sym_return_statement = 30,
  sym_body = 31,
  sym_variable_declaration = 32,
  sym_variable_declarator = 33,
  sym__expressions = 34,
  sym_member_expression = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_log_statement_repeat1 = 37,
  aux_sym_class_body_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_log] = "log",
  [anon_sym_COMMA] = ",",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_class] = "class",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_return] = "return",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [sym_literal] = "literal",
  [sym_number] = "number",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_log_statement] = "log_statement",
  [sym_if_statement] = "if_statement",
  [sym_elif_statement] = "elif_statement",
  [sym_else_statement] = "else_statement",
  [sym_class_declaration] = "class_declaration",
  [sym__suite] = "_suite",
  [sym_class_body] = "class_body",
  [sym_method_definition] = "method_definition",
  [sym_param_list] = "param_list",
  [sym_return_statement] = "return_statement",
  [sym_body] = "body",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_declarator] = "variable_declarator",
  [sym__expressions] = "_expressions",
  [sym_member_expression] = "member_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_log_statement_repeat1] = "log_statement_repeat1",
  [aux_sym_class_body_repeat1] = "class_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_log] = anon_sym_log,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_literal] = sym_literal,
  [sym_number] = sym_number,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_log_statement] = sym_log_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_elif_statement] = sym_elif_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_class_declaration] = sym_class_declaration,
  [sym__suite] = sym__suite,
  [sym_class_body] = sym_class_body,
  [sym_method_definition] = sym_method_definition,
  [sym_param_list] = sym_param_list,
  [sym_return_statement] = sym_return_statement,
  [sym_body] = sym_body,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_declarator] = sym_variable_declarator,
  [sym__expressions] = sym__expressions,
  [sym_member_expression] = sym_member_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_log_statement_repeat1] = aux_sym_log_statement_repeat1,
  [aux_sym_class_body_repeat1] = aux_sym_class_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_log] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_log_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elif_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_class_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__suite] = {
    .visible = false,
    .named = true,
  },
  [sym_class_body] = {
    .visible = true,
    .named = true,
  },
  [sym_method_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator] = {
    .visible = true,
    .named = true,
  },
  [sym__expressions] = {
    .visible = false,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_log_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_expression = 1,
  field_name = 2,
  field_object = 3,
  field_params = 4,
  field_property = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_expression] = "expression",
  [field_name] = "name",
  [field_object] = "object",
  [field_params] = "params",
  [field_property] = "property",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_object, 0},
    {field_property, 2},
  [4] =
    {field_name, 0},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 7,
  [12] = 8,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 19,
  [28] = 23,
  [29] = 25,
  [30] = 21,
  [31] = 20,
  [32] = 32,
  [33] = 24,
  [34] = 34,
  [35] = 34,
  [36] = 22,
  [37] = 26,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 39,
  [46] = 46,
  [47] = 40,
  [48] = 43,
  [49] = 41,
  [50] = 44,
  [51] = 42,
  [52] = 46,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 70,
  [72] = 69,
  [73] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\'') ADVANCE(1);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == '=') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_log);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 3},
  [57] = {.lex_state = 0, .external_lex_state = 3},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_log] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(67),
    [sym__definition] = STATE(5),
    [sym_log_statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_elif_statement] = STATE(5),
    [sym_else_statement] = STATE(5),
    [sym_class_declaration] = STATE(5),
    [sym_return_statement] = STATE(5),
    [sym_variable_declaration] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_log] = ACTIONS(5),
    [anon_sym_if] = ACTIONS(7),
    [anon_sym_elif] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_class] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(15),
    [anon_sym_const] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      anon_sym_log,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(25), 1,
      anon_sym_else,
    ACTIONS(27), 1,
      anon_sym_class,
    ACTIONS(29), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      anon_sym_const,
    ACTIONS(33), 1,
      sym_dedent,
    STATE(64), 1,
      sym_body,
    STATE(6), 9,
      sym__definition,
      sym_log_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_class_declaration,
      sym_return_statement,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [39] = 9,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_log,
    ACTIONS(40), 1,
      anon_sym_if,
    ACTIONS(43), 1,
      anon_sym_elif,
    ACTIONS(46), 1,
      anon_sym_else,
    ACTIONS(49), 1,
      anon_sym_class,
    ACTIONS(52), 1,
      anon_sym_return,
    ACTIONS(55), 1,
      anon_sym_const,
    STATE(3), 9,
      sym__definition,
      sym_log_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_class_declaration,
      sym_return_statement,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [75] = 9,
    ACTIONS(35), 1,
      sym_dedent,
    ACTIONS(58), 1,
      anon_sym_log,
    ACTIONS(61), 1,
      anon_sym_if,
    ACTIONS(64), 1,
      anon_sym_elif,
    ACTIONS(67), 1,
      anon_sym_else,
    ACTIONS(70), 1,
      anon_sym_class,
    ACTIONS(73), 1,
      anon_sym_return,
    ACTIONS(76), 1,
      anon_sym_const,
    STATE(4), 9,
      sym__definition,
      sym_log_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_class_declaration,
      sym_return_statement,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [111] = 9,
    ACTIONS(5), 1,
      anon_sym_log,
    ACTIONS(7), 1,
      anon_sym_if,
    ACTIONS(9), 1,
      anon_sym_elif,
    ACTIONS(11), 1,
      anon_sym_else,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      anon_sym_return,
    ACTIONS(17), 1,
      anon_sym_const,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(3), 9,
      sym__definition,
      sym_log_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_class_declaration,
      sym_return_statement,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [147] = 9,
    ACTIONS(19), 1,
      anon_sym_log,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(25), 1,
      anon_sym_else,
    ACTIONS(27), 1,
      anon_sym_class,
    ACTIONS(29), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      anon_sym_const,
    ACTIONS(81), 1,
      sym_dedent,
    STATE(4), 9,
      sym__definition,
      sym_log_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_class_declaration,
      sym_return_statement,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [183] = 6,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(94), 1,
      sym_dedent,
    ACTIONS(91), 2,
      sym_literal,
      sym_number,
    STATE(7), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(86), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [211] = 6,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      sym_dedent,
    ACTIONS(102), 2,
      sym_literal,
      sym_number,
    STATE(7), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(98), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [239] = 6,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      sym_dedent,
    ACTIONS(108), 2,
      sym_literal,
      sym_number,
    STATE(8), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(106), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [267] = 6,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 2,
      sym_literal,
      sym_number,
    STATE(12), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(106), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [295] = 6,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(124), 2,
      sym_literal,
      sym_number,
    STATE(11), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(86), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [323] = 6,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(127), 2,
      sym_literal,
      sym_number,
    STATE(11), 3,
      sym__expressions,
      sym_member_expression,
      aux_sym_log_statement_repeat1,
    ACTIONS(98), 7,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [351] = 3,
    ACTIONS(133), 1,
      anon_sym_DOT,
    ACTIONS(131), 4,
      sym_dedent,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(129), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [371] = 3,
    ACTIONS(135), 1,
      anon_sym_DOT,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(129), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [391] = 2,
    ACTIONS(94), 4,
      sym_dedent,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(86), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [408] = 2,
    ACTIONS(139), 4,
      sym_dedent,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(137), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [425] = 2,
    ACTIONS(94), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(86), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [442] = 2,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_literal,
      sym_number,
    ACTIONS(137), 8,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
      sym_identifier,
  [459] = 1,
    ACTIONS(141), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [470] = 1,
    ACTIONS(143), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [481] = 1,
    ACTIONS(145), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [492] = 1,
    ACTIONS(147), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [503] = 1,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [514] = 1,
    ACTIONS(151), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [525] = 1,
    ACTIONS(153), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [536] = 1,
    ACTIONS(155), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [547] = 1,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [558] = 1,
    ACTIONS(149), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [569] = 1,
    ACTIONS(153), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [580] = 1,
    ACTIONS(145), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [591] = 1,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [602] = 1,
    ACTIONS(157), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [613] = 1,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [624] = 1,
    ACTIONS(159), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [635] = 1,
    ACTIONS(159), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [646] = 1,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [657] = 1,
    ACTIONS(155), 8,
      sym_dedent,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [668] = 1,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      anon_sym_log,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_class,
      anon_sym_return,
      anon_sym_const,
  [679] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(163), 2,
      sym_literal,
      sym_number,
    STATE(9), 2,
      sym__expressions,
      sym_member_expression,
  [691] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(165), 2,
      sym_literal,
      sym_number,
    STATE(34), 2,
      sym__expressions,
      sym_member_expression,
  [703] = 4,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_dedent,
    STATE(20), 1,
      sym_class_body,
    STATE(54), 2,
      sym_method_definition,
      aux_sym_class_body_repeat1,
  [717] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(171), 2,
      sym_literal,
      sym_number,
    STATE(30), 2,
      sym__expressions,
      sym_member_expression,
  [729] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(173), 2,
      sym_literal,
      sym_number,
    STATE(32), 2,
      sym__expressions,
      sym_member_expression,
  [741] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(175), 2,
      sym_literal,
      sym_number,
    STATE(24), 2,
      sym__expressions,
      sym_member_expression,
  [753] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 2,
      sym_literal,
      sym_number,
    STATE(10), 2,
      sym__expressions,
      sym_member_expression,
  [765] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(181), 2,
      sym_literal,
      sym_number,
    STATE(17), 2,
      sym__expressions,
      sym_member_expression,
  [777] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(183), 2,
      sym_literal,
      sym_number,
    STATE(35), 2,
      sym__expressions,
      sym_member_expression,
  [789] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(185), 2,
      sym_literal,
      sym_number,
    STATE(38), 2,
      sym__expressions,
      sym_member_expression,
  [801] = 4,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(187), 1,
      sym_dedent,
    STATE(31), 1,
      sym_class_body,
    STATE(55), 2,
      sym_method_definition,
      aux_sym_class_body_repeat1,
  [815] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(189), 2,
      sym_literal,
      sym_number,
    STATE(33), 2,
      sym__expressions,
      sym_member_expression,
  [827] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(191), 2,
      sym_literal,
      sym_number,
    STATE(21), 2,
      sym__expressions,
      sym_member_expression,
  [839] = 3,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(193), 2,
      sym_literal,
      sym_number,
    STATE(15), 2,
      sym__expressions,
      sym_member_expression,
  [851] = 3,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym_dedent,
    STATE(53), 2,
      sym_method_definition,
      aux_sym_class_body_repeat1,
  [862] = 3,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(200), 1,
      sym_dedent,
    STATE(53), 2,
      sym_method_definition,
      aux_sym_class_body_repeat1,
  [873] = 3,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(202), 1,
      sym_dedent,
    STATE(53), 2,
      sym_method_definition,
      aux_sym_class_body_repeat1,
  [884] = 1,
    ACTIONS(204), 3,
      sym_indent,
      sym_dedent,
      sym_identifier,
  [890] = 2,
    ACTIONS(208), 1,
      sym_indent,
    ACTIONS(206), 2,
      sym_dedent,
      sym_identifier,
  [898] = 2,
    ACTIONS(210), 1,
      sym_indent,
    STATE(19), 1,
      sym__suite,
  [905] = 2,
    ACTIONS(212), 1,
      sym_indent,
    STATE(27), 1,
      sym__suite,
  [912] = 2,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(23), 1,
      sym_variable_declarator,
  [919] = 1,
    ACTIONS(216), 2,
      sym_dedent,
      sym_identifier,
  [924] = 2,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    STATE(57), 1,
      sym_param_list,
  [931] = 2,
    ACTIONS(220), 1,
      sym_identifier,
    STATE(28), 1,
      sym_variable_declarator,
  [938] = 1,
    ACTIONS(222), 2,
      sym_dedent,
      sym_identifier,
  [943] = 1,
    ACTIONS(224), 2,
      sym_dedent,
      sym_identifier,
  [948] = 1,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
  [952] = 1,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
  [956] = 1,
    ACTIONS(230), 1,
      sym_identifier,
  [960] = 1,
    ACTIONS(232), 1,
      sym_identifier,
  [964] = 1,
    ACTIONS(234), 1,
      anon_sym_EQ,
  [968] = 1,
    ACTIONS(236), 1,
      anon_sym_EQ,
  [972] = 1,
    ACTIONS(238), 1,
      sym_identifier,
  [976] = 1,
    ACTIONS(240), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 75,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 183,
  [SMALL_STATE(8)] = 211,
  [SMALL_STATE(9)] = 239,
  [SMALL_STATE(10)] = 267,
  [SMALL_STATE(11)] = 295,
  [SMALL_STATE(12)] = 323,
  [SMALL_STATE(13)] = 351,
  [SMALL_STATE(14)] = 371,
  [SMALL_STATE(15)] = 391,
  [SMALL_STATE(16)] = 408,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 442,
  [SMALL_STATE(19)] = 459,
  [SMALL_STATE(20)] = 470,
  [SMALL_STATE(21)] = 481,
  [SMALL_STATE(22)] = 492,
  [SMALL_STATE(23)] = 503,
  [SMALL_STATE(24)] = 514,
  [SMALL_STATE(25)] = 525,
  [SMALL_STATE(26)] = 536,
  [SMALL_STATE(27)] = 547,
  [SMALL_STATE(28)] = 558,
  [SMALL_STATE(29)] = 569,
  [SMALL_STATE(30)] = 580,
  [SMALL_STATE(31)] = 591,
  [SMALL_STATE(32)] = 602,
  [SMALL_STATE(33)] = 613,
  [SMALL_STATE(34)] = 624,
  [SMALL_STATE(35)] = 635,
  [SMALL_STATE(36)] = 646,
  [SMALL_STATE(37)] = 657,
  [SMALL_STATE(38)] = 668,
  [SMALL_STATE(39)] = 679,
  [SMALL_STATE(40)] = 691,
  [SMALL_STATE(41)] = 703,
  [SMALL_STATE(42)] = 717,
  [SMALL_STATE(43)] = 729,
  [SMALL_STATE(44)] = 741,
  [SMALL_STATE(45)] = 753,
  [SMALL_STATE(46)] = 765,
  [SMALL_STATE(47)] = 777,
  [SMALL_STATE(48)] = 789,
  [SMALL_STATE(49)] = 801,
  [SMALL_STATE(50)] = 815,
  [SMALL_STATE(51)] = 827,
  [SMALL_STATE(52)] = 839,
  [SMALL_STATE(53)] = 851,
  [SMALL_STATE(54)] = 862,
  [SMALL_STATE(55)] = 873,
  [SMALL_STATE(56)] = 884,
  [SMALL_STATE(57)] = 890,
  [SMALL_STATE(58)] = 898,
  [SMALL_STATE(59)] = 905,
  [SMALL_STATE(60)] = 912,
  [SMALL_STATE(61)] = 919,
  [SMALL_STATE(62)] = 924,
  [SMALL_STATE(63)] = 931,
  [SMALL_STATE(64)] = 938,
  [SMALL_STATE(65)] = 943,
  [SMALL_STATE(66)] = 948,
  [SMALL_STATE(67)] = 952,
  [SMALL_STATE(68)] = 956,
  [SMALL_STATE(69)] = 960,
  [SMALL_STATE(70)] = 964,
  [SMALL_STATE(71)] = 968,
  [SMALL_STATE(72)] = 972,
  [SMALL_STATE(73)] = 976,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_log_statement, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log_statement, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_log_statement, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log_statement, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expressions, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expressions, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, 0, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_declaration, 3, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__suite, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_body, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_body, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elif_statement, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 2, 0, 4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_definition, 4, 0, 4),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [228] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_indent = 0,
  ts_external_token_dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token_dedent] = true,
  },
  [3] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
  },
  [4] = {
    [ts_external_token_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_firescript_external_scanner_create(void);
void tree_sitter_firescript_external_scanner_destroy(void *);
bool tree_sitter_firescript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_firescript_external_scanner_serialize(void *, char *);
void tree_sitter_firescript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_firescript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_firescript_external_scanner_create,
      tree_sitter_firescript_external_scanner_destroy,
      tree_sitter_firescript_external_scanner_scan,
      tree_sitter_firescript_external_scanner_serialize,
      tree_sitter_firescript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
